### ISSUE TITLE
Admin API Progress

### ISSUE THREAD

**Issue by subotic** [dhlab-basel/Knora#553]
The following list will provide an easier overview of what is implemented and what is still missing. Also, it provides the information if the feature is already available in `develop` or implemented in a PR (which would require using a specific branch).

### User

- [x] Get all users (develop)
- [x] Get single user (develop)
- [x] Change basic user information (name, password, etc.) (#486)
- [x] Add user to project (#486)
- [x] Change user SystemAdmin status (#486)

### Projects

- [x] Get all projects (develop)
- [x] Get single project (by IRI and by Shortname) (develop)
- [x] Get project members (#486)
- [x] Create project (develop)
- [x] Change basic project information (develop)

### Groups

- [x] Get all groups (develop)
- [x] Get single group (by IRI and by ProjectIri and Shortname) (develop)
- [x] Get group members (#486)
- [x] Create group (#486)
- [x] Change basic group information (#486)

### Permissions

- [x] Get DOA permissions (develop)
- [x] Get administrative permissions (develop)
- [ ] Create DOA permissions
- [ ] Change DOA permissions
- [ ] Create administrative permissions
- [ ] Change administrative permissions

### Lists

- [x] Get whole list (develop)
- [x] Get single item (develop)
- [ ] List all lists bellonging to a single project
- [ ] Create new list
- [ ] Add item to list
- [ ] Rename list item
- [ ] Reposition list item

**Comment by subotic** [comment]
Depends on: #486

**Comment by subotic** [comment]
Depends on: #572

**Comment by kilchenmann** [comment]
I get wrong ontology iris in the ProjectResponse. 
For example: I make a project info request for incunabula
`http://0.0.0.0:3333/admin/projects/http%3A%2F%2Frdfh.ch%2Fprojects%2F0803` and I get an array of ontologies:
`["http://www.knora.org/ontology/0803/incunabula"]`

But when I want to use this IRI to get the ontology information (e.g. /allentities)
`
http://0.0.0.0:3333/v2/ontologies/allentities/http%3A%2F%2Fwww.knora.org%2Fontology%2F0803%2Fincunabula`

I get the following response:
```
{
    "error": "org.knora.webapi.BadRequestException: Invalid ontology IRI: http://www.knora.org/ontology/0803/incunabula"
}

The ontology IRI in this project should be `http://0.0.0.0:3333/ontology/0803/incunabula/v2`

So, how should we fix this?

**Comment by benjamingeer** [comment]
The admin API uses internal IRIs (the ones used in the triplestore) rather than API v2's external IRIs. Not sure of the best way to deal with this.

**Comment by kilchenmann** [comment]
I'm sure @subotic has a solution. 

Otherwise I have to make two requests (and the ontology IRIs in project object are useless): 
1. /v2/ontologies/metadata to get the ontology IRIs
2. /v2/ontologies/allentities

**Comment by subotic** [comment]
I see two possibilities:

- 1 you transform them to V2 in the GUI
- 1 I transform them to V2 in the API

What happens when we have `V3`, `V4`, etc. ontology IRIs? What should the admin API return then?

It would be a small function in the GUI to transform an internal ontology IRI to an external V2 ontology IRI: replace `www.knora.org` with `host:port` and append `/v2`.

**Comment by benjamingeer** [comment]
> replace www.knora.org with host:port and append /v2.

That only works for project-specific ontologies. For a built-in Knora ontology, the external hostname is always `api.knora.org`. Also, the external name of the `knora-base` ontology is `knora-api`.

Seems error-prone to have this knowledge in more than one place. I don’t see the harm in doing two requests as @kilchenmann said, especially since the GUI caches ontologies.

**Comment by subotic** [comment]
Does it maybe make sense to return in the admin API both, the internal and external ontology IRIs?

Or when requesting the project info, tell the API that you would like to have internal or external v2 /v3 /vx ontology IRIs.

Anyhow, this will take a moment to implement. So the fastest way, for now, would be to make a second request, as @benjamingeer suggested.

**Comment by benjamingeer** [comment]
> Does it maybe make sense to return in the admin API both, the internal and external ontology IRIs?
>
> Or when requesting the project info, tell the API that you would like to have internal or external v2 /v3 /vx ontology IRIs.

Either would be easy to do. To get an IRI in any schema you like, you just have to do something like `iri.toSmartIri.toOntologySchema(ApiV2WithValueObjects)`.
