### ISSUE TITLE
Ben's issue queue

### ISSUE THREAD

**Issue by benjamingeer** [dhlab-basel/Knora#571]
What I'm currently working on, in descending order of priority:

- [ ] #561 Importing Pictures over API with Python
- [ ] #563 SPARQL update for bulk import causes GraphDB stack overflow
- [ ] https://github.com/dhlab-basel/Sipi/pull/198 fix (sipi): serveral bugs
- [ ] #509 Convert old SALSAH data to XML for import into Knora
- [ ] #566 Add project/dataset metadata ontology to knora
- [ ] #567 search the content of a resource's label in advanced search
- [ ] #524 Add an untyped key-value store backed by the triplestore
- [ ] #392 Express and enforce constraints on standoff tag nesting
